[octocore.cs.uh.edu:13957] [[24860,1],0] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file ../../orte/util/nidmap.c at line 118
[octocore.cs.uh.edu:13957] [[24860,1],0] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file ../../../../../orte/mca/ess/env/ess_env_module.c at line 174
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_util_nidmap_init failed
  --> Returned value Data unpack would read past end of buffer (-26) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
[octocore.cs.uh.edu:13957] [[24860,1],0] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file ../../orte/runtime/orte_init.c at line 128
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_set_name failed
  --> Returned value Data unpack would read past end of buffer (-26) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: orte_init failed
  --> Returned "Data unpack would read past end of buffer" (-26) instead of "Success" (0)
--------------------------------------------------------------------------
[octocore.cs.uh.edu:13957] *** An error occurred in MPI_Init_thread
[octocore.cs.uh.edu:13957] *** on a NULL communicator
[octocore.cs.uh.edu:13957] *** Unknown error
[octocore.cs.uh.edu:13957] *** MPI_ERRORS_ARE_FATAL: your MPI job will now abort
[octocore.cs.uh.edu:13958] [[24860,1],1] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file ../../orte/util/nidmap.c at line 118
[octocore.cs.uh.edu:13958] [[24860,1],1] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file ../../../../../orte/mca/ess/env/ess_env_module.c at line 174
--------------------------------------------------------------------------
An MPI process is aborting at a time when it cannot guarantee that all
of its peer processes in the job will be killed properly.  You should
double check that everything has shut down cleanly.

  Reason:     Before MPI_INIT completed
  Local host: octocore.cs.uh.edu
  PID:        13957
--------------------------------------------------------------------------
[octocore.cs.uh.edu:13958] [[24860,1],1] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file ../../orte/runtime/orte_init.c at line 128
--------------------------------------------------------------------------
mpirun has exited due to process rank 0 with PID 13957 on
node octocore.cs.uh.edu exiting without calling "finalize". This may
have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).
--------------------------------------------------------------------------
[octocore.cs.uh.edu:13956] 1 more process has sent help message help-orte-runtime.txt / orte_init:startup:internal-failure
[octocore.cs.uh.edu:13956] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[octocore.cs.uh.edu:13956] 1 more process has sent help message help-orte-runtime / orte_init:startup:internal-failure
[octocore.cs.uh.edu:13956] 1 more process has sent help message help-mpi-runtime / mpi_init:startup:internal-failure
[octocore.cs.uh.edu:13956] 1 more process has sent help message help-mpi-errors.txt / mpi_errors_are_fatal unknown handle
[octocore.cs.uh.edu:13956] 1 more process has sent help message help-mpi-runtime.txt / ompi mpi abort:cannot guarantee all killed
